language: python
cache: false
python:
  # We don't actually use the Travis Python, but this keeps it organized.
 #- "2.6"
  - "2.7"
 #- "3.2"
 #- "3.3"
 #- "3.4"
 - "3.5"
 #- "3.5-dev" # 3.5 development branch

notifications:
    email: false
 
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  # The next couple lines fix a crash with multiprocessing on Travis and are
  # not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda create --name TestEnv python=$TRAVIS_PYTHON_VERSION atlas numpy scipy cython
  - source activate TestEnv
  - python -c "import os; print('\n'.join(map(str, os.environ.items())))"
  - python setup.py install
  # removing local libraries to be sure the installation is correct
  - rm -rf ./compmech/lib
  - rm -rf ./compmech/include

# running tests
script:
  # activating the TestEnv is not setting this environment variable
  - export PYTHONPATH=/home/travis/miniconda/envs/TestEnv/lib/python${TRAVIS_PYTHON_VERSION}/site-packages:$PYTHONPATH
  #- ls -la  ../../../virtualenv/python2.7.9/lib/python2.7/site-packages
  # useful to get all environment variables
  - python -c "import os;print('\n'.join(map(str, os.environ.items())))"
  - py.test --cache-clear
