# thanks to http://conda.pydata.org/docs/travis.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
 #- "2.6"
  - "2.7"
 #- "3.2"
 #- "3.3"
 #- "3.4"
 #- "3.5"
 #- "3.5-dev" # 3.5 development branch
 #
 
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION atlas numpy scipy cython
  - source activate test-environment
  - python setup.py install

# command to run tests
script:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION atlas numpy scipy cython
  - source activate test-environment
  - py.test
